services:
  node-app:
    container_name: hive_db_backend
    build: ./
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5435
    ports:
      - "3001:3001"