version: '3.9'

services:
  websocket:
    build: .
    container_name: websocket_server
    restart: unless-stopped
    ports:
      - "3001:3001"   # Cambia si tu server usa otro puerto
    environment:
      - NODE_ENV=production
